### ISSUE TITLE
Non-clickable link in user document

### ISSUE THREAD

**Issue by Binz-Z** [NCI-CGR/GEMSCAN#14]
The user document "Running_on_NIH_Biowulf" section, "create config/samples.txt and config/config.yaml as described in **here**", The "here" is not clickable because it will move to next line when mouse over it.

**Comment by shukwong** [comment]
modified in https://github.com/NCI-CGR/GEMSCAN/commit/2835c309583a601485233f51f89ddff7db056a45
@Binz-Z could you take a look?

**Comment by Binz-Z** [comment]
It looks fine now. Thanks, Wendy.
