### ISSUE TITLE
Which vcf/gvcf files to keep? 

### ISSUE THREAD

**Issue by shukwong** [NCI-CGR/GEMSCAN#5]
Strelka2 and DeepVariant produce both vcf and gvcf files for each sample and currently, both are kept. Is it necessary to keep both or just the per sample gvcf files is enough?

GATK Haplotyper produces gvcf files and they are genotyped into vcf files, currently the gvcf files are marked as temp.
If we do switch to using GLnexus merge for GATK Haplotype caller we may want to keep the per sample gvcf files for future merging.

**Comment by Binz-Z** [comment]
Yes. No need to keep both files. I see some potential needs for people to access individual called VCF files. Any concern if we remove gvcf but keep VCF?

**Comment by shukwong** [comment]
If we remove gvcf we won't be able to merge samples should there be additional samples after the run.

**Comment by Binz-Z** [comment]
Ah. How could I miss the N+1 part ;).  Looks like we may need to keep both files. VCF can be removed during the archival time. Is it easy for user to general VCF file from gvcf if needed? Thanks!
